[default]
auto_detect_solc = true
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_difficulty = 0
block_number = 1
block_timestamp = 1
bytecode_hash = 'none'
cache = true
cache_path = 'cache'
evm_version = 'london'
extra_output = []
extra_output_files = []
ffi = false
force = false
fuzz_max_global_rejects = 65536
fuzz_max_local_rejects = 1024
fuzz_runs = 1024
gas_limit = 9223372036854775807
gas_price = 0
gas_reports = ['*']
ignored_error_codes = [1878]
initial_balance = '0xffffffffffffffffffffffff'
libraries = []
libs = ['node_modules', 'test/dapp_test/src']
memory_limit = 33554432
names = false
no_storage_caching = false
offline = false
optimizer = true
optimizer_runs = 1024
out = 'out'
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@rari-capital/=node_modules/@rari-capital/',
    'hardhat/=node_modules/hardhat/',
    "ds-test/=test/dapp_test/lib/ds-test/src/"
]
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
sizes = false
sparse_mode = false
src = 'contracts'
test = 'test'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
verbosity = 3
via_ir = false
