# I have no clue if this works
# Chats that led me here: https://dapphub.chat/channel/dev?msg=SjN9jmkiXFuKaFqWM and https://dapphub.chat/channel/dev?msg=HnZi8PHXquyzZ35cX 
# So based it off of: https://github.com/centrifuge/tinlake-maker-lib/blob/c47b6e1b17e3e3d58036ad7356bec34370edccd4/.github/workflows/build.yml

name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest,]
        # we need this to map platform names as used by github to
        # the attribute names defined in release.nix
        include:
          - os: ubuntu-latest
            os_attr: linux
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - uses: cachix/install-nix-action@ef4324316b96b50b4671cecef9ecc6fd286f224a
        with:
          skip_adding_nixpkgs_channel: false        
      - uses: cachix/cachix-action@6e4751ed42b22f60165d3f266cfa4cce66ae406d
        with:
          name: dapp
          skipPush: true
          signingKey: ''
      - name: install
        run: nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA solc-static-versions.solc_0_7_5
      - name: test
        run: nix-shell --pure --command "make test"